### ISSUE TITLE
Remove border of textfield

### ISSUE THREAD

**Issue by bernhardwaidacher** [thiagoross/TRCurrencyTextField#5]
Is it possible to remove the border of the textfield?
I've tried in the interface builder and in code and it is still there

**Comment by bernhardwaidacher** [comment]
Nevermind, was my mistake. Doing it in code works. Great work by the way!

**Comment by thiagorossener** [comment]
Thank you @bernhardwaidacher, I'm glad you liked it. I don't see the code for a while, but any question please just ask.
